spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health, info