eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

server:
  port: 9090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://auth-service:9000
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter
        - id: book-service
          uri: http://book-service:9002
          predicates:
            - Path=/api/books/**
          filters:
            - AuthenticationFilter
        - id: author-service
          uri: http://author-service:9004
          predicates:
            - Path=/api/authors/**
          filters:
            - AuthenticationFilter
